import datetime

apd_store_version = '1.0.1'
apd_store_data_path = 'E:\\Projects\\APD\\PythonProject\\'
apd_gp_utm_data_files = [
        {'period':'period 1','source_type':'Third-party referrals','filename':apd_store_data_path + 'play_store_performance\\daily_performance.csv'},
  
    ]
apd_gp_data_files = [
{'group':'group 1','period':'period 10','source_type':'Google Play explore','filename':apd_store_data_path + 'play_store_performance(1)\\daily_performance.csv'},
{'group':'group 1','period':'period 10','source_type':'Google Play search','filename':apd_store_data_path + 'play_store_performance(2)\\daily_performance.csv'},
{'group':'group 1','period':'period 10','source_type':'Third-party referrals','filename':apd_store_data_path + 'play_store_performance(3)\\daily_performance.csv'},
{'group':'group 2','period':'period 10','source_type':'Google Play explore','filename':apd_store_data_path + 'play_store_performance(4)\\daily_performance.csv'},
{'group':'group 2','period':'period 10','source_type':'Google Play search','filename':apd_store_data_path + 'play_store_performance(5)\\daily_performance.csv'},
{'group':'group 2','period':'period 10','source_type':'Third-party referrals','filename':apd_store_data_path + 'play_store_performance(6)\\daily_performance.csv'},
{'group':'group 3','period':'period 10','source_type':'Google Play explore','filename':apd_store_data_path + 'play_store_performance(7)\\daily_performance.csv'},
{'group':'group 3','period':'period 10','source_type':'Google Play search','filename':apd_store_data_path + 'play_store_performance(8)\\daily_performance.csv'},
{'group':'group 3','period':'period 10','source_type':'Third-party referrals','filename':apd_store_data_path + 'play_store_performance(9)\\daily_performance.csv'},

    ]

apd_ios_store_files = [
    apd_store_data_path + 'APD-App Referrer First-Time Downloads.csv',
    apd_store_data_path + 'APD-App Referrer Product Page Views.csv',
    apd_store_data_path + 'APD-App Store Browse First-Time Downloads.csv',
    apd_store_data_path + 'APD-App Store Browse Product Page Views.csv',
    apd_store_data_path + 'APD-App Store Browse Total Downloads.csv',
    apd_store_data_path + 'APD-App Store Search First-Time Downloads.csv',
    apd_store_data_path + 'APD-App Store Search Product Page Views.csv',
    apd_store_data_path + 'APD-App Store Search Total Downloads.csv',
    apd_store_data_path + 'APD-Web Referrer First-Time Downloads.csv',
    apd_store_data_path + 'APD-Web Referrer Product Page Views.csv',
    apd_store_data_path + 'APD-App Referrer Total Downloads.csv',
    apd_store_data_path + 'APD-Web Referrer Total Downloads.csv',

]
now = datetime.datetime.now()
date_today = ("%d-%.2d-%.2d %.2d-%.2d" % (now.year, now.month, now.day, now.hour, now.minute))
now_3 = now- datetime.timedelta(days=3)
now_4 = now- datetime.timedelta(days=4)
date_today_3 = datetime.date.today()- datetime.timedelta(days=3)
str_date_3 = ("%d%.2d%.2d" % (now_3.year, now_3.month, now_3.day))

str_today = ("%d-%.2d-%.2d" % (now.year, now.month, now.day))

iMaxStoreDataRows = 90 #check 30 days

user        = "SAI_METABASE_PREPROCESS"
password    = "CZ-F74VEHDvM9Ma5!nG^EkbDJ"
account     = "gameloft.eu-west-1"
db          = "ELEPHANT_DB"
importWarehouse = "METABASE_WH"
schema      = "APPLAYDU"
store_table      = "STORE_STATS"


download_path = "g:\\Jenkin\\APD_preprocess\\auto_email\\assets\\"

snowflake_data_files = {
    'download'           :download_path + "\\out_snowflake_store_20210817_%s.csv"%(str_date_3)
    }
aaf_tasks = [
    {
        'sql':"SQLs/10.Download Snowflake Store data.sql"
    }
]
apd_country = ['Russian Federation','India','Brazil','Mexico','Indonesia','Italy','United States','China','Turkey','Germany','France','Ukraine','Philippines','Poland','Argentina','United Kingdom','Spain','Korea, Republic of','Malaysia','Thailand','Romania']
                     
COUNTRY_NAME= {
 "AD": "Andorra",
"AE": "United Arab Emirates",
"AF": "Afghanistan",
"AG": "Antigua and Barbuda",
"AI": "Anguilla",
"AL": "Albania",
"AM": "Armenia",
"AN": "Netherlands Antilles",
"AO": "Angola",
"AQ": "Antarctica",
"AR": "Argentina",
"AS": "American Samoa",
"AT": "Austria",
"AU": "Australia",
"AW": "Aruba",
"AX": "Aland Islands",
"AZ": "Azerbaijan",
"BA": "Bosnia and Herzegowina",
"BB": "Barbados",
"BD": "Bangladesh",
"BE": "Belgium",
"BF": "Burkina Faso",
"BG": "Bulgaria",
"BH": "Bahrain",
"BI": "Burundi",
"BJ": "Benin",
"BL": "Saint Barthelemy",
"BM": "Bermuda",
"BN": "Brunei Darussalam",
"BO": "Bolivia",
"BQ": "Bonaire, Sint Eustatius and Saba",
"BR": "Brazil",
"BS": "Bahamas",
"BT": "Bhutan",
"BV": "Bouvet Island",
"BW": "Botswana",
"BY": "Belarus",
"BZ": "Belize",
"CA": "Canada",
"CC": "Cocos (Keeling) Islands",
"CD": "Democratic Republic of the Congo",
"CF": "Central African Republic",
"CG": "Congo",
"CH": "Switzerland",
"CI": "Cote D\\\'Ivoire",
"CK": "Cook Islands",
"CL": "Chile",
"CM": "Cameroon",
"CN": "China",
"CO": "Colombia",
"CP": "Clipperton Island",
"CR": "Costa Rica",
"CS": "Kosovo",
"CU": "Cuba",
"CV": "Cape Verde",
"CW": "Curaçao",
"CX": "Christmas Island",
"CY": "Cyprus",
"CZ": "Czech Republic",
"DE": "Germany",
"DJ": "Djibouti",
"DK": "Denmark",
"DM": "Dominica",
"DO": "Dominican Republic",
"DT": "DOM-TOM",
"DZ": "Algeria",
"EC": "Ecuador",
"EE": "Estonia",
"EG": "Egypt",
"EH": "Western Sahara",
"ER": "Eritrea",
"ES": "Spain",
"ET": "Ethiopia",
"FI": "Finland",
"FJ": "Fiji",
"FK": "Falkland Islands (Malvinas)",
"FM": "Micronesia, Federated States of",
"FO": "Faroe Islands",
"FR": "France",
"GA": "Gabon",
"GB": "United Kingdom",
"GD": "Grenada",
"GE": "Georgia",
"GF": "French Guiana",
"GG": "Guernsey",
"GH": "Ghana",
"GI": "Gibraltar",
"GL": "Greenland",
"GM": "Gambia",
"GN": "Guinea",
"GP": "Guadeloupe",
"GQ": "Equatorial Guinea",
"GR": "Greece",
"GS": "South Georgia and the South Sandwich Islands",
"GT": "Guatemala",
"GU": "Guam",
"GW": "Guinea-bissau",
"GY": "Guyana",
"HK": "Hong Kong",
"HM": "Heard and Mc Donald Islands",
"HN": "Honduras",
"HR": "Croatia",
"HT": "Haiti",
"HU": "Hungary",
"IC": "Canary Islands",
"ID": "Indonesia",
"IE": "Ireland",
"IL": "Israel",
"IM": "Isle of Man",
"IN": "India",
"IO": "British Indian Ocean Territory",
"IQ": "Iraq",
"IR": "Iran (Islamic Republic of)",
"IS": "Iceland",
"IT": "Italy",
"JE": "Jersey",
"JM": "Jamaica",
"JO": "Jordan",
"JP": "Japan",
"KE": "Kenya",
"KG": "Kyrgyzstan",
"KH": "Cambodia",
"KI": "Kiribati",
"KM": "Comoros",
"KN": "Saint Kitts and Nevis",
"KP": "Korea, Democratic People\'s Republic of",
"KR": "Korea, Republic of",
"KW": "Kuwait",
"KY": "Cayman Islands",
"KZ": "Kazakhstan",
"LA": "Lao People\'s Democratic Republic",
"LB": "Lebanon",
"LC": "Saint Lucia",
"LI": "Liechtenstein",
"LK": "Sri Lanka",
"LR": "Liberia",
"LS": "Lesotho",
"LT": "Lithuania",
"LU": "Luxembourg",
"LV": "Latvia",
"LY": "Libyan Arab Jamahiriya",
"MA": "Morocco",
"MC": "Monaco",
"MD": "Moldova, Republic of",
"ME": "Montenegro",
"MF": "Saint Martin",
"MG": "Madagascar",
"MH": "Marshall Islands",
"MK": "Macedonia, The Former Yugoslav Republic of",
"ML": "Mali",
"MM": "Myanmar",
"MN": "Mongolia",
"MO": "Macau",
"MP": "Northern Mariana Islands",
"MQ": "Martinique",
"MR": "Mauritania",
"MS": "Montserrat",
"MT": "Malta",
"MU": "Mauritius",
"MV": "Maldives",
"MW": "Malawi",
"MX": "Mexico",
"MY": "Malaysia",
"MZ": "Mozambique",
"N/A": "Undefined",
"NA": "Namibia",
"NC": "New Caledonia",
"NE": "Niger",
"NF": "Norfolk Island",
"NG": "Nigeria",
"NI": "Nicaragua",
"NL": "Netherlands",
"NO": "Norway",
"NP": "Nepal",
"NR": "Nauru",
"NU": "Niue",
"NZ": "New Zealand",
"OM": "Oman",
"PA": "Panama",
"PE": "Peru",
"PF": "French Polynesia",
"PG": "Papua New Guinea",
"PH": "Philippines",
"PK": "Pakistan",
"PL": "Poland",
"PM": "St. Pierre and Miquelon",
"PN": "Pitcairn",
"PR": "Puerto Rico",
"PS": "Palestinian Territory",
"PT": "Portugal",
"PW": "Palau",
"PY": "Paraguay",
"QA": "Qatar",
"RE": "Reunion",
"RO": "Romania",
"RS": "Serbia",
"RU": "Russian Federation",
"RW": "Rwanda",
"SA": "Saudi Arabia",
"SB": "Solomon Islands",
"SC": "Seychelles",
"SD": "Sudan",
"SE": "Sweden",
"SG": "Singapore",
"SH": "St. Helena",
"SI": "Slovenia",
"SJ": "Svalbard and Jan Mayen Islands",
"SK": "Slovakia (Slovak Republic)",
"SL": "Sierra Leone",
"SM": "San Marino",
"SN": "Senegal",
"SO": "Somalia",
"SR": "Suriname",
"SS": "South Sudan",
"ST": "Sao Tome and Principe",
"SV": "El Salvador",
"SX": "Sint Maarten",
"SY": "Syrian Arab Republic",
"SZ": "Swaziland",
"TC": "Turks and Caicos Islands",
"TD": "Chad",
"TF": "French Southern Territories",
"TG": "Togo",
"TH": "Thailand",
"TJ": "Tajikistan",
"TK": "Tokelau",
"TL": "Timor-Leste",
"TM": "Turkmenistan",
"TN": "Tunisia",
"TO": "Tonga",
"TP": "East Timor",
"TR": "Turkey",
"TT": "Trinidad and Tobago",
"TV": "Tuvalu",
"TW": "Taiwan, Province of China",
"TZ": "Tanzania, United Republic of",
"UA": "Ukraine",
"UG": "Uganda",
"UM": "United States Minor Outlying Islands",
"US": "United States",
"UY": "Uruguay",
"UZ": "Uzbekistan",
"VA": "Vatican City State (Holy See)",
"VC": "Saint Vincent and the Grenadines",
"VE": "Venezuela",
"VG": "Virgin Islands (British)",
"VI": "Virgin Islands (U.S.)",
"VN": "Viet Nam",
"VU": "Vanuatu",
"WF": "Wallis and Futuna Islands",
"WS": "Samoa",
"YE": "Yemen",
"YT": "Mayotte",
"YU": "Yugoslavia",
"ZA": "South Africa",
"ZM": "Zambia",
"ZR": "Zaire",
"ZW": "Zimbabwe",

        "XK": "Kosovo", #tuan.dm
        "KV": "Kosovo", #tuan.dm
    }
COUNTRY_CODE = {
   "Andorra": "AD",
"United Arab Emirates": "AE",
"Afghanistan": "AF",
"Antigua and Barbuda": "AG",
"Anguilla": "AI",
"Albania": "AL",
"Armenia": "AM",
"Netherlands Antilles": "AN",
"Angola": "AO",
"Antarctica": "AQ",
"Argentina": "AR",
"American Samoa": "AS",
"Austria": "AT",
"Australia": "AU",
"Aruba": "AW",
"Aland Islands": "AX",
"Azerbaijan": "AZ",
"Bosnia and Herzegowina": "BA",
"Bosnia and Herzegovina": "BA",
"Barbados": "BB",
"Bangladesh": "BD",
"Belgium": "BE",
"Burkina Faso": "BF",
"Bulgaria": "BG",
"Bahrain": "BH",
"Burundi": "BI",
"Benin": "BJ",
"Saint Barthelemy": "BL",
"Bermuda": "BM",
"Brunei": "BN",
"Brunei Darussalam": "BN",
"Bolivia": "BO",
"Bonaire, Sint Eustatius and Saba": "BQ",
"Brazil": "BR",
"Bahamas": "BS",
"Bhutan": "BT",
"Bouvet Island": "BV",
"Botswana": "BW",
"Belarus": "BY",
"Belize": "BZ",
"Canada": "CA",
"Cocos (Keeling) Islands": "CC",
"Democratic Republic of the Congo": "CD",
"Central African Republic": "CF",
"Congo, Republic of the": "CG",
"Congo": "CG",
"Switzerland": "CH",
"Cote d'Ivoire": "CI",
"Cote D'Ivoire": "CI",
"Cook Islands": "CK",
"Chile": "CL",
"Cameroon": "CM",
"China mainland": "CN",
"China": "CN",
"Colombia": "CO",
"Clipperton Island": "CP",
"Costa Rica": "CR",
"Kosovo": "KV",
"Cuba": "CU",
"Cape Verde": "CV",
"Curaçao": "CW",
"Christmas Island": "CX",
"Cyprus": "CY",
"Czech Republic": "CZ",
"Germany": "DE",
"Djibouti": "DJ",
"Denmark": "DK",
"Dominica": "DM",
"Dominican Republic": "DO",
"DOM-TOM": "DT",
"Algeria": "DZ",
"Ecuador": "EC",
"Estonia": "EE",
"Egypt": "EG",
"Western Sahara": "EH",
"Eritrea": "ER",
"Spain": "ES",
"Ethiopia": "ET",
"Finland": "FI",
"Fiji": "FJ",
"Falkland Islands (Malvinas)": "FK",
"Micronesia, Federated States of": "FM",
"Faroe Islands": "FO",
"France": "FR",
"Gabon": "GA",
"United Kingdom": "GB",
"Grenada": "GD",
"Georgia": "GE",
"French Guiana": "GF",
"Guernsey": "GG",
"Ghana": "GH",
"Gibraltar": "GI",
"Greenland": "GL",
"Gambia": "GM",
"Guinea": "GN",
"Guadeloupe": "GP",
"Equatorial Guinea": "GQ",
"Greece": "GR",
"South Georgia and the South Sandwich Islands": "GS",
"Guatemala": "GT",
"Guam": "GU",
"Guinea-bissau": "GW",
"Guyana": "GY",
"Hong Kong": "HK",
"Heard and Mc Donald Islands": "HM",
"Honduras": "HN",
"Croatia": "HR",
"Haiti": "HT",
"Hungary": "HU",
"Canary Islands": "IC",
"Indonesia": "ID",
"Ireland": "IE",
"Israel": "IL",
"Isle of Man": "IM",
"India": "IN",
"British Indian Ocean Territory": "IO",
"Iraq": "IQ",
"Iran (Islamic Republic of)": "IR",
"Iceland": "IS",
"Italy": "IT",
"Jersey": "JE",
"Jamaica": "JM",
"Jordan": "JO",
"Japan": "JP",
"Kenya": "KE",
"Kyrgyzstan": "KG",
"Cambodia": "KH",
"Kiribati": "KI",
"Comoros": "KM",
"Saint Kitts and Nevis": "KN",
"Korea, Democratic People's Republic of": "KP",
"Korea, Republic of": "KR",
"Kuwait": "KW",
"Cayman Islands": "KY",
"Kazakhstan": "KZ",
"Lao People's Democratic Republic": "LA",
"Lebanon": "LB",
"Saint Lucia": "LC",
"Liechtenstein": "LI",
"Sri Lanka": "LK",
"Liberia": "LR",
"Lesotho": "LS",
"Lithuania": "LT",
"Luxembourg": "LU",
"Latvia": "LV",
"Libya": "LY", #tuan.dm
"Libyan Arab Jamahiriya": "LY",
"Morocco": "MA",
"Monaco": "MC",
"Moldova": "MD", #tuan.dm
"Moldova, Republic of": "MD",
"Montenegro": "ME",
"Saint Martin": "MF",
"Madagascar": "MG",
"Marshall Islands": "MH",
"Macedonia, The Former Yugoslav Republic of": "MK",
"North Macedonia": "MK",
"Mali": "ML",
"Myanmar": "MM",
"Mongolia": "MN",
"Macau": "MO",
"Northern Mariana Islands": "MP",
"Martinique": "MQ",
"Mauritania": "MR",
"Montserrat": "MS",
"Malta": "MT",
"Mauritius": "MU",
"Maldives": "MV",
"Malawi": "MW",
"Mexico": "MX",
"Malaysia": "MY",
"Mozambique": "MZ",
"Undefined": "N/A",
"Namibia": "NA",
"New Caledonia": "NC",
"Niger": "NE",
"Norfolk Island": "NF",
"Nigeria": "NG",
"Nicaragua": "NI",
"Netherlands": "NL",
"Norway": "NO",
"Nepal": "NP",
"Nauru": "NR",
"Niue": "NU",
"New Zealand": "NZ",
"Oman": "OM",
"Panama": "PA",
"Peru": "PE",
"French Polynesia": "PF",
"Papua New Guinea": "PG",
"Philippines": "PH",
"Pakistan": "PK",
"Poland": "PL",
"St. Pierre and Miquelon": "PM",
"Pitcairn": "PN",
"Puerto Rico": "PR",
"Palestinian Territory": "PS",
"Portugal": "PT",
"Palau": "PW",
"Paraguay": "PY",
"Qatar": "QA",
"Reunion": "RE",
"Romania": "RO",
"Serbia": "RS",
"Russia": "RU",
"Russian": "RU",
"Russian Federation": "RU",
"Rwanda": "RW",
"Saudi Arabia": "SA",
"Solomon Islands": "SB",
"Seychelles": "SC",
"Sudan": "SD",
"Sweden": "SE",
"Singapore": "SG",
"St. Helena": "SH",
"Slovenia": "SI",
"Svalbard and Jan Mayen Islands": "SJ",
"Slovakia (Slovak Republic)": "SK",
"Slovakia": "SK",
"Sierra Leone": "SL",
"San Marino": "SM",
"Senegal": "SN",
"Somalia": "SO",
"Suriname": "SR",
"South Sudan": "SS",
"Sao Tome and Principe": "ST",
"El Salvador": "SV",
"Sint Maarten": "SX",
"Syrian Arab Republic": "SY",
"Swaziland": "SZ",
"Turks and Caicos Islands": "TC",
"Chad": "TD",
"French Southern Territories": "TF",
"Togo": "TG",
"Thailand": "TH",
"Tajikistan": "TJ",
"Tokelau": "TK",
"Timor-Leste": "TL",
"Turkmenistan": "TM",
"Tunisia": "TN",
"Tonga": "TO",
"East Timor": "TP",
"Turkey": "TR",
"Trinidad and Tobago": "TT",
"Tuvalu": "TV",
"Taiwan": "TW",
"Taiwan, Province of China": "TW",
"Tanzania, United Republic of": "TZ",
"Ukraine": "UA",
"Uganda": "UG",
"United States Minor Outlying Islands": "UM",
"United States": "US",
"Uruguay": "UY",
"Uzbekistan": "UZ",
"Vatican City State (Holy See)": "VA",
"Saint Vincent and the Grenadines": "VC",
"Venezuela": "VE",
"Virgin Islands (British)": "VG",
"Virgin Islands (U.S.)": "VI",
"Viet Nam": "VN",
"Vietnam": "VN",
"Vanuatu": "VU",
"Wallis and Futuna Islands": "WF",
"Samoa": "WS",
"Yemen": "YE",
"Mayotte": "YT",
"Yugoslavia": "YU",
"South Africa": "ZA",
"Zambia": "ZM",
"Zaire": "ZR",
"Zimbabwe": "ZW",
    }
